Task.create(status: "test1", content: "test1")
Task.create(status: "test2", content: "test2")
Task.create(status: "test3", content: "test3")
Task.create(status: "test4", content: "test4")
Task.create(status: "test5", content: "test5")
Task.create(status: "test6", content: "test6")